### ISSUE TITLE
405 or 401 error

### ISSUE THREAD

**Issue by recou** [maercu/dnac2teams#2]
Should the URL configuration in DNAC be:

https://$DNAC-IP:5000/prod/dnac2teams

or

https://$DNAC-IP:5000/

?

For the first i'm getting a 401, for the second a 405 error.

"POST /prod/dnac2teams HTTP/1.1" 401 -
"POST / HTTP/1.1" 405 -

PS: i've added the mandatory ssl support:
```
if __name__ == '__main__':
    app.run(debug=True, host="0.0.0.0", ssl_context='adhoc')
```

**Comment by ldev** [comment]
We had the same problem you are facing. It ended up being the "apitoken = os.getenv("AUTH_TOKEN")" line, and that the envinronment variable was not set when changing from HTTP to HTTPS.

Found out by inserting some temp debug output to flaskapp.py:

```
def requires_auth(f):
    def decorated(*args, **kwargs):
        xauthtoken = request.headers.get('X-Auth-Token')
        if xauthtoken and xauthtoken == apitoken:
            return f(*args, **kwargs)
        else:
            return {'message': 'Unauthorized. DEBUG: xauthtoken: %s, apitoken: %s' % (xauthtoken, apitoken)}, 401
    return decorated
```

Ended up with running the flask app with our own internal certs:

```
if __name__ == '__main__':
    app.run(debug=True, host="0.0.0.0", ssl_context=('cert.pem', 'key.pem'))
```

**Comment by recou** [comment]
thank you, creating certs did the trick
